### ISSUE TITLE
Some USB Cables don't work

### ISSUE THREAD

**Issue by JellyTitan** [JellyTitan/Sofle-Pico#14]
Some USB cables don't work. I'm not sure why. Anybody got any ideas?

**Comment by TheWerle** [comment]
Which sort of cables specifically?  USB-C to USB-A? USB-C to USB-C?  

Don't work as in "no power" or "no device recognition"? 

Cheap cables shipped for charging toys/lights/gadgets sometimes leave out the data-wires or don't actually implement the reversible pinout on the USB-C connectors.

**Comment by JellyTitan** [comment]
I've been slumming it with cheap off-brand Pico's. (Which is how I found out that not all of the generic clones have a diode between vbus & vsys!)
I have a 'trash cable' usb-c to usb-c, that works with this [tenstar Pico](https://www.aliexpress.us/item/3256805868694592.html), but not with this [even cheaper clone](https://www.aliexpress.us/item/3256805606949884.html).

I'm not getting any power with that specific trash cable, but switching cables makes everything work.

I would swear this happened at least once with an earlier prototype, but i didn't make note of it.

I think your comment about the cheap cables not implementing the reversable pin-out is the probable cause. It had never occured to me to 'flip-over' a USB-C cable. I'll try that next time!

**Comment by TheWerle** [comment]
Yeah, for both the sake of power delivery and general lack of confusion its worth stealing a halfway decent cable.  Any spares from USB-C cellphones will likely be fine as they'll be guaranteed to have all the connections and thicker wire suitable for USB3.0 Power Delivery

**Comment by JellyTitan** [comment]
Thanks! I appreciate the advice. I've added notes about this in the troubleshooting section.
