### ISSUE TITLE
VIA: Screen content upside down

### ISSUE THREAD

**Issue by uberrice** [JellyTitan/Sofle-Pico#26]
Hiya. Decided to check out the new VIA FW. Looking good so far. Removes the need to reflash everything all the time!

However, at least on the version of the board I ordered, the left screen seems to be upside-down. I have the screen mounted exactly as you do in the main picture: https://github.com/JellyTitan/Sofle-Pico/blob/main/docs/images/build_guide_pico/sofle_pico_v3.4_hero.jpeg . Top side, round holes, screen wraps around on the left. Yet, plugging in the left side of the board, the screen is upside down / rotated in the wrong direction. Was this some change in newer revisions, or is the VIA code borked? Or do I simply have a weird screen?

**Comment by JellyTitan** [comment]
Great catch! It looks like I missed an OLED rotation in the default keymap. (I've been neglecting that in leiu of my own weird preferences).
Default:
![image](https://github.com/JellyTitan/Sofle-Pico/assets/72168556/13eae11f-9f7b-4a1f-a21c-2bbd0ffb8ca3)

JellyTitan:
![image](https://github.com/JellyTitan/Sofle-Pico/assets/72168556/00f95967-eb3e-4d28-9238-63e321ba61b1)

I'll see if I can't fix that while I'm working on some other OLED cleanup tasks.

**Comment by JellyTitan** [comment]
I've fixed the OLED rotation and regenerated the .uf2 files. Give it a shot now:
https://github.com/JellyTitan/Sofle-Pico/tree/main/Sofle_Pico/Firmware

**Comment by uberrice** [comment]
Yup, that fixed it. One thing that still remains: Not sure if it is just my board (remember I had some magic smoke appearing when first building it....) but when the master is the right board, the boot image doesn't seem to work correctly. The 'Sofle Pico' logo just builds slowly, filling up the 'white noise' present in the rest of the screen, and the QMK/VIA logo only builds around 2/3rds.

Could you test that on your own boards as well?

**Comment by uberrice** [comment]
Also just submitted a pull request for a small bug with the CPSLK placement on screen to your qmk_firmware repo

**Comment by JellyTitan** [comment]
Sadly, I think it's a magic smoke related issue. I tested both the `default_via` and the `jellytitan` builds, and the boot image works as expected when the right hand is master. 

`jellytitan` RH boot
![29F7E3FA-F94D-459D-97AD-FE33985A7BB0_4_5005_c](https://github.com/JellyTitan/Sofle-Pico/assets/72168556/a71609fb-257c-4da8-a4c9-5eb2579160e6)


`default_via` RH boot
![B35F2253-1DE3-4A6B-AB94-4BF6C923B26C_4_5005_c](https://github.com/JellyTitan/Sofle-Pico/assets/72168556/a85e121a-2f99-43a4-b216-3ade60b4456f)

`default_via` RH as master
![E3C750DF-2938-4453-9482-964E303D600A_4_5005_c](https://github.com/JellyTitan/Sofle-Pico/assets/72168556/f3db4443-072c-4ab1-9c3e-20902c9e11b8)

I'll take a look at the Cpslk PR.
