### ISSUE TITLE
Set handedness via pin

### ISSUE THREAD

**Issue by JellyTitan** [JellyTitan/Sofle-Pico#27]
During QMK PR, [Drashna recommended](https://github.com/qmk/qmk_firmware/pull/23338#discussion_r1544082255) setting [handedness via pin](https://github.com/qmk/qmk_firmware/blob/master/docs/feature_split_keyboard.md#handedness-by-pin). We certainly have enough spare pins to do this. I tried setting this up on an earlier iteration, found it would likely need a pull up resistor, then abandoned the idea.
Revisit if time permits.

**Comment by JellyTitan** [comment]
@theWerle - any chance you'd consider integrating handedness by pin to the Choc variant?

**Comment by TheWerle** [comment]
Seems straight-forward enough, yeah.  

If you want to adopt the TRRS protection circuit I included in the baseline then the easiest solution is to lean into the power-chain handedness and direct the user to assign MASTER_LEFT or MASTER_RIGHT in their userspace config.h file. 

If you keep the baseline without that circuit, a pullup or pulldown would be added to left or right.  GP28 is a natural candidate as it has nearby 3V3 and GND pins. You could wire a resistor from the unused poka-yoke pads for the Pico and the OLED or add explicit footprints in a new rev.   
![image](https://github.com/JellyTitan/Sofle-Pico/assets/159328578/1b1cc2a1-aa0b-4f28-b152-607c2285142a)


Based on the current schematic the "cleanest" method for would be adding a pull resistor from GP28 to 3V3 or GND at the patch bay, or alternatively using GPIO18

**Comment by JellyTitan** [comment]
Thank you for the help! I've been giving it some thought - and I think it's more important to keep the QMK momentum going than it is to add in the handedness feature. 

I really would prefer to incorporate this - but for the sake of time, I'm gonna go with the handedness by `#define` method, and let it default to Left hand master. I think I'll probably incorporate this when I have a chance to fold in some of the excellent stuff you've done on the Choc variant. (I might [avoid GP28](https://docs.google.com/spreadsheets/d/1LPjy6F5lHfUkmsrM5zlZmc5auYy5YBakW8Awe6hYFWo/edit#gid=0) though)

**Comment by JellyTitan** [comment]
May include in future revisions, for now, trying to get QMK PR approved.

**Comment by TheWerle** [comment]
> Thank you for the help! I've been giving it some thought - and I think it's more important to keep the QMK momentum going than it is to add in the handedness feature.
> 
> I really would prefer to incorporate this - but for the sake of time, I'm gonna go with the handedness by `#define` method, and let it default to Left hand master. I think I'll probably incorporate this when I have a chance to fold in some of the excellent stuff you've done on the Choc variant. (I might [avoid GP28](https://docs.google.com/spreadsheets/d/1LPjy6F5lHfUkmsrM5zlZmc5auYy5YBakW8Awe6hYFWo/edit#gid=0) though)
Yeah, trusting the default seems to make the most sense.  Easy enough for users to add their own #define if they want to switch to the right-hand. I know I've seen folks mention needing pointing devices to be on the master for consistent performance if using autodetecting mouse layers, but I don't know if that's still the case with "SPLIT_POINTING_ENABLE".  Are there other common features with the requirement for strict handedness?

**Comment by JellyTitan** [comment]
I haven't seen many strict handedness requirements - but I'm usually only looking at the feature I'm working on. 
Since QMK changes so quickly, I don't really trust the docs anymore. I usually search the `/keyboards` folder to find an example and crib what I'm after.

**Comment by JellyTitan** [comment]
Defaulting to Master Left for now. May add support for this in future revisions.
