### ISSUE TITLE
 Both halves really want to be the right half

### ISSUE THREAD

**Issue by Lego047** [JellyTitan/Sofle-Pico#42]
Not sure whats going on as my first one is working just fine on the same firmware but the 2nd one I built just doesnt want to have a left half as the main

**Comment by Lego047** [comment]
i had a dumb brain moment and forgot how to set each side and was just flashing a right side file to both

**Comment by JellyTitan** [comment]
No worries! You're not alone in the hand-flash mixup. QMK discourages seperate files for LH/RH, so we updated the official PR to default to LH master, resulting in a single image for both hands. The PR is still in review though, so that firmare hasn't been released yet.  Some day . . .

**Comment by Lego047** [comment]
probably also didnt help i was using a pretty modified, and i think outdated version of the via code for it to be a vial keymap, but for future reference i guess what youre suppose to do now for support with eeprom sides is run 
```
make sofle_pico:keymap:uf2-split-left
make sofle_pico:keymap:uf2-split-right 
```
